### ISSUE TITLE
Update bot scripts to support `mongodb database` implementation

### ISSUE THREAD

**Issue by kaxada** [badging/bot-scripts#7]
This includes installing dependencies and providing the necessary inputs to the `envvars` that are used for the `db connection`

**Comment by FaithKovi** [comment]
Hello @kaxada I am interested in working on this. Please assign.

**Comment by kaxada** [comment]
Hello @FaithKovi this issue is still pending given the fact that we haven't reached the implementation and integration of the database like we anticipated but soon we hope to come back here since we are scaling to using the website. Otherwise let me point you to what you can do in this script
